### ISSUE TITLE
URL to access airflow GUI

### ISSUE THREAD

**Issue by chandran-git** [Cloud-Innovation-Partners/miniBRS#58]
Reference document did not mention how to access airflow after installation, in order to configure Source tables, frequency parameters, target storage we would like to access GUI to configure. if it i mentioned in document would be helpful

**Comment by shahbaz-ali** [comment]
Thanks @chandran-git for raising the issue, I see we have missed GUI access information on the docs. We shall be updating the installation docs page with information to access GUI for both automated and manual installation hope that satisfies the need.
