### ISSUE TITLE
Reference link in result dataset

### ISSUE THREAD

**Issue by chandran-git** [Cloud-Innovation-Partners/miniBRS#59]
Output dataset has the link rather than actual value, it is because of the field type. if it is reference field then it is extracted with hyperlink to the referenced field. it can be resolved by setting the below parameters to true 

sysparm_display_value and sysparm_exclude_reference_link

**Comment by shahbaz-ali** [comment]
@md-akeel you were parsing the file to exclude the reference_link in case of database operators. I think @chandran-git  has suggested something that may save your time and resource, please have a look if your operators can adapt to these changes.

**Comment by md-akeel** [comment]
Yes we can adapt these changes in database operators. We will adapt these changes in the next patch version. Thanks @chandran-git for the suggestion. Thanks @shahbaz-ali
